import { useParams, useNavigate } from 'react-router-dom';
import { 
  ArrowLeftIcon, 
  ShieldCheckIcon, 
  DevicePhoneMobileIcon, 
  GlobeAltIcon, 
  ClockIcon,
  ShieldExclamationIcon,
  DocumentMagnifyingGlassIcon
} from '@heroicons/react/24/outline';

export default function AccessLogDetails() {
  const { id } = useParams();
  const navigate = useNavigate();

  // Mock data based on ID
  const logData: any = {
    '1': { title: 'Reddington Hospital', action: 'viewed SNH Lab Result', time: '2hr ago', date: 'April 7, 2026', color: 'bg-[#22C55E]', location: 'Lagos, Nigeria', ip: '192.168.1.45', device: 'Hospital Workstation (Chrome/Windows)', type: 'Verified Provider' },
    '2': { title: 'St. Nicholas Hospital', action: 'gained access to medical history', time: 'Yesterday', date: 'April 6, 2026', color: 'bg-[#FACC15]', location: 'Lagos Island, Nigeria', ip: '41.203.77.12', device: 'iPad Pro (Safari/iOS)', type: 'Emergency Access' },
    '3': { title: 'Igandon General Hospital', action: 'viewed YFB Vaccination', time: '2 days ago', date: 'April 5, 2026', color: 'bg-[#EF4444]', location: 'Alimosho, Nigeria', ip: '102.89.2.21', device: 'Android Tablet (Chrome)', type: 'Verified Provider' },
    '4': { title: 'Dr. Adeyemi', action: 'added a new prescription', time: 'Last week', date: 'March 15, 2026', color: 'bg-[#3B82F6]', location: 'Victoria Island, Nigeria', ip: '105.112.33.8', device: 'iPhone 15 (Mobile App)', type: 'Verified Doctor' },
  };

  const log = logData[id || '1'] || logData['1'];

  return (
    <div className="space-y-6 font-sora">
      <button onClick={() => navigate('/dashboard/access-log')} className="flex items-center gap-2 text-gray-400 hover:text-[#6183FF] transition-all group">
        <ArrowLeftIcon className="w-4 h-4" />
        <span className="font-bold text-sm">Back to Access Log</span>
      </button>

      <div className="bg-white rounded-[40px] border border-gray-50 shadow-xl shadow-blue-500/5 overflow-hidden">
        {/* Header */}
        <div className="p-10 border-b border-gray-50 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div className="flex items-center gap-5">
            <div className={`w-14 h-14 rounded-2xl ${log.color} flex items-center justify-center shadow-lg shadow-blue-500/10`}>
              <DocumentMagnifyingGlassIcon className="w-8 h-8 text-white" />
            </div>
            <div>
              <h2 className="text-2xl font-black text-[#101217] tracking-tight">{log.title}</h2>
              <p className="text-gray-400 font-medium text-sm">{log.type}</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className="bg-green-50 text-green-600 text-[10px] font-black uppercase tracking-widest px-4 py-2 rounded-full border border-green-100 flex items-center gap-2">
              <ShieldCheckIcon className="w-4 h-4" /> Secure Session
            </span>
          </div>
        </div>

        {/* Details Grid */}
        <div className="p-10 md:p-14">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
            <div className="space-y-10">
              <div>
                <h3 className="text-[10px] font-black text-gray-300 uppercase tracking-[0.2em] mb-4">Activity Summary</h3>
                <div className="bg-gray-50 rounded-3xl p-6 border border-gray-100">
                  <p className="text-[#101217] font-bold text-lg mb-2">"{log.action}"</p>
                  <p className="text-gray-400 text-sm font-medium">This action was authorized via a temporary QR access token generated by the patient.</p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-8">
                <div>
                  <h4 className="text-[10px] font-black text-gray-300 uppercase tracking-widest mb-2 flex items-center gap-2">
                    <ClockIcon className="w-3 h-3" /> Timestamp
                  </h4>
                  <p className="font-bold text-[#101217]">{log.date}</p>
                  <p className="text-xs text-gray-400 font-medium">{log.time}</p>
                </div>
                <div>
                  <h4 className="text-[10px] font-black text-gray-300 uppercase tracking-widest mb-2 flex items-center gap-2">
                    <GlobeAltIcon className="w-3 h-3" /> Geolocation
                  </h4>
                  <p className="font-bold text-[#101217]">{log.location}</p>
                  <p className="text-xs text-gray-400 font-medium">IP: {log.ip}</p>
                </div>
              </div>
            </div>

            <div className="space-y-10">
              <div>
                <h3 className="text-[10px] font-black text-gray-300 uppercase tracking-[0.2em] mb-4">Device Verification</h3>
                <div className="flex items-center gap-4 p-6 border border-gray-100 rounded-3xl">
                  <div className="w-12 h-12 bg-[#EEF2FF] rounded-2xl flex items-center justify-center shadow-inner">
                    <DevicePhoneMobileIcon className="w-6 h-6 text-[#6183FF]" />
                  </div>
                  <div>
                    <p className="font-bold text-[#101217] text-sm">{log.device}</p>
                    <p className="text-[10px] font-black text-green-500 uppercase tracking-widest mt-1">Encrypted Connection</p>
                  </div>
                </div>
              </div>

              <div className="bg-red-50/50 rounded-3xl p-8 border border-red-100/50">
                <div className="flex items-center gap-3 mb-4">
                  <ShieldExclamationIcon className="w-6 h-6 text-red-500" />
                  <h3 className="text-sm font-black text-red-600 uppercase tracking-widest">Security Controls</h3>
                </div>
                <p className="text-xs text-red-700/60 font-medium mb-6 leading-relaxed">
                  If you do not recognize this activity, your account security might be compromised. 
                  Revoking access will immediately invalidate all active sessions for this provider.
                </p>
                <button 
                  onClick={() => {
                    if (window.confirm(`Revoke all future access for ${log.title}?`)) {
                      alert('Access revoked. Security team has been notified.');
                      navigate('/dashboard/access-log');
                    }
                  }}
                  className="w-full bg-red-500 text-white font-bold py-4 rounded-2xl shadow-lg shadow-red-500/20 hover:bg-red-600 transition-all"
                >
                  Revoke Provider Access
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
